---
abstract: 'a distribution of modules to handle locale codes'
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Locale-Codes
provides:
  Locale::Codes:
    file: lib/Locale/Codes.pm
    version: 3.11
  Locale::Codes::Country:
    file: lib/Locale/Codes/Country.pm
    version: 3.11
  Locale::Codes::Currency:
    file: lib/Locale/Codes/Currency.pm
    version: 3.11
  Locale::Codes::Language:
    file: lib/Locale/Codes/Language.pm
    version: 3.11
  Locale::Codes::Script:
    file: lib/Locale/Codes/Script.pm
    version: 3.11
  Locale::Constants:
    file: lib/Locale/Constants.pm
    version: 3.11
  Locale::Country:
    file: lib/Locale/Country.pm
    version: 3.11
  Locale::Currency:
    file: lib/Locale/Currency.pm
    version: 3.11
  Locale::Language:
    file: lib/Locale/Language.pm
    version: 3.11
  Locale::Script:
    file: lib/Locale/Script.pm
    version: 3.11
requires:
  Carp: 0
  constant: 0
  perl: 5.002
resources:
  license: http://dev.perl.org/licenses/
version: 3.11
