perl -I../lib alias_code.t 1
perl -I../lib code2country.t 1
perl -I../lib code2currency.t 1
perl -I../lib code2language.t 1
perl -I../lib code2script.t 1
perl -I../lib country2code.t 1
perl -I../lib country_code2code.t 1
perl -I../lib currency2code.t 1
perl -I../lib language2code.t 1
perl -I../lib rename_country.t 1
perl -I../lib script2code.t 1
